FROM node:16
WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y nano git
RUN git clone https://github.com/BonhyeonGu/HLS_server hls_srv

WORKDIR /usr/src/app/hls_srv/server
RUN npm install
EXPOSE 12000
#CMD [ "node", "index.js" ]
ENTRYPOINT ["/bin/sh", "-c" , "tail -f /dev/null"]